name: Build & Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Version tag (ex: v1.0.0)"
        required: true
        type: string

jobs:
  deploy:
    uses: voikyrioh/dashboard/.github/workflows/build-deploy.yml@main
    with:
      app-name: slay-the-slime
      tag: ${{ inputs.tag }}
    secrets: inherit
