name: Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: "Type de release"
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch

jobs:
  release:
    uses: voikyrioh/infra-as-code/.github/workflows/ci-release.yml@main
    with:
      app_name: slay_the_slime
      bump_type: ${{ inputs.bump_type }}
    secrets: inherit
    permissions:
      contents: write
      packages: write
